### ISSUE TITLE
 source and transform nodesTypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by ljairath** [pedrouid/gatsby-source-vimeo#5]
Hi Pedro

Getting following error. Googled but no solution yet. Thank you..
```sh
success open and validate gatsby-configs — 0.012 s
success load plugins — 0.472 s
success onPreInit — 5.735 s
success delete html and css files from previous builds — 0.043 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success initialize cache — 0.463 s
success copy gatsby files — 0.686 s
success onPreBootstrap — 0.008 s
⠂ source and transform nodesStarting to fetch data from Drupal
⠐ source and transform nodesTypeError: Cannot read property 'match' of null
    at parseVideos (/home/vide/node_modules/gatsby-source-vimeo/gatsby-node.js:50:6)
    at videos.forEach.video (/home/vide/node_modules/gatsby-source-vimeo/gatsby-node.js:117:40)
    at Array.forEach (<anonymous>)
    at Object.exports.sourceNodes (/home/vide/node_modules/gatsby-source-vimeo/gatsby-node.js:117:12)
```
config.js
```javascript
{
      resolve: `gatsby-source-vimeo`,
      options: {
        clientID: `66d177164e9fcd0fe6f524fd397fb78c5e8`,
        clientSecret: `3eM1xdwse80YeYnYLqRPN4CMzyd/7bdvXnYrB0HOtlJbV36LQKOuCdsaREVx+YRgbTK6JNLa4d1A67vKk+1NXTCHIB5O
082uavu1PQ0t5isUlKNLyu3lY4Y`,
        userID: `92043621`,
        //searchQuery: 'INSERT_SEARCH_QUERY [OPTIONAL]',
        transformer (video) {
        // Transform the video data [OPTIONAL]
        // i.e. Add extra fields or alter existing field
          video.newField = 'value'
          return video
        }
```

**Comment by pedrouid** [comment]
Hi @ljairath, I'm not really sure. Are you using Gatsby v2? I haven't test it yet

**Comment by ljairath** [comment]
Hi Pedro
Thanks for your prompt response. Really appreciated.
:~/vide$ gatsby -v
2.4.8
Best wishes,
LJ


________________________________

**Comment by ljairath** [comment]
gatsby -v
2.4.8
